version: '3.9'

services:
  database_donadoce:
    image: 'postgres:13-alpine'
    container_name: database_donadoce
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres
  # app:
  #   build: .
  #   container_name: api_dona_doce
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database_donadoce #nome do serviço do banco
  #   depends_on:
  #     - database_donadoce #nome do serviço do banco
  
volumes:
  pgdata:
    driver: local